#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

echo "==> Checking EAS login..."
if ! eas whoami &>/dev/null; then
  echo "Not logged in. Running 'eas login'..."
  eas login
fi

echo "==> Current user: $(eas whoami)"

# Generate buildInfo.ts
VERSION=$(node -p "require('./package.json').version")
BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
COMMIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
cat > src/buildInfo.ts << EOF
// AUTO-GENERATED — do not edit (regenerated by build.sh before each build)
export const BUILD_INFO = {
  version: '${VERSION}',
  buildDate: '${BUILD_DATE}',
  commitHash: '${COMMIT_HASH}',
};
EOF
echo "==> Generated buildInfo.ts (v${VERSION}, ${BUILD_DATE}, ${COMMIT_HASH})"

# If --ota flag passed, push a JS-only OTA update instead of a full build.
# Use this for pure JS/TS fixes that don't touch native modules.
# Requires the app to have been built with expo-updates at least once.
if [[ "${1:-}" == "--ota" ]]; then
  echo "==> Pushing OTA update to 'preview' channel..."
  eas update --branch preview --message "${2:-fix}" --non-interactive
  echo "==> OTA update pushed. Users will receive it on next app launch."
  exit 0
fi

echo "==> Starting iOS preview build (internal distribution)..."
echo "    You will receive an install link / QR code when the build finishes."
echo "    Tip: for JS-only fixes, run:  bash build.sh --ota 'description'"
echo ""

npm install --legacy-peer-deps --silent
eas build --platform ios --profile preview --non-interactive
